---
- hosts: localhost
  connection: local
  sudo: yes
  vars:
  - myvars: hostvars['{{ ansible_fqdn }}']
  tasks:

  - name: Package install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
    - apt-transport-https
    - monit

  - name: Docker repository
    copy: src=files/docker.list
      dest=/etc/apt/sources.list.d/docker.list

  - name: Import the repository key
    apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

  - name: Docker install
    apt: name=lxc-docker state=present update_cache=yes

  - name: add GEE user
    user: name=gee shell=/bin/bash groups=docker,root append=yes

  - name: add public keys
    authorized_key:
      user=gee
      key="{{ item }}"
    with_items:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDs5KFS/ZoOVevr7aa8PdhrSFjCS2eCak2Ze1O8PpvLD9vH8np0sfzpzZBTTRw2RGrfaoOQg/RjVdAhVfa9OAncepnj6awWCUIdks0xmb19PZBEq/Y0TW/rpWfFsQLKJkHjtEfPMhcyYW3DoyP5NkXxOYPPQsRGQawFa5K0BdaMLSZpTJxNqIvU4yutfo9UeaT/9rGvYOreChXf/hXk8bKr9NRERCr8RCglw009R/8aMvxr1GI1oFAiPMOyXD719TVCSENciIX8bdhnlpqBZ8rTtbDUb+gult3HZ+ivBVBY7BkHJDsj90py96k5bQDfiu8uVVvn9wYYABvlcnMfuN99 ubuntu@test"
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArlgZWcRP75W2/e5bKG1FEeec1OJQuw9dGVyo3TdUgVu4F0/JgBsgR2BrTuQ+mzm+N47ZkSrYwLdAJGuvL7ECxc6aouQ6AtQ/biU1gsrfuPnnUBjfAGqlP/L77lYxpLAPglx/HCCBu53gLKVt8lRDyyGZaWnB7fGlnwrn5AMjcfXsz5Ia8W6oBmxy2fxDSR9SpTs5yAzfcj37mCBtOZBwdjb54B36WpFq9BwFrEXxbvxH4aU0WSneJagicZuCUXnTg2YSURBD0jBmTrYOVRfTZzNPyagOvuIhnnakOSGkGa8s4SrC5zymZsVPdQbp6icRsu6OjKZ83Y0oiTQ4rTaeUw== acb@cadenza.cs.princeton.edu'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1HQWcDWkJYsuLu/YEwyg6H91Jy6fPbAt+WZd9oeZ+50eV37dcIZJbOALdztdrbbDCjbpFhzwsHAnzef7zV+nFhpA/bXt9JUjeGc3CEJAh9854rjoVT7lobnhi2WQHNpVOPgAPEwG4myH09tgrM+KVgDx26Zbrf7ExX7Q96ivxVmOMSoV63+0EuTClPQJ3z6j3ImGBbOz2+mybyTFlpFP4UOi8tnSOFhjhSOijcbMwru5jWUUg9M/WW2L81k/hV1hLCvbLJ6+dAq2JYoLocRBEYHLQBOF4g8VCA0WhwwjNEwK+k7Ax6CBu+37K26rz/pH8xHTKDX3IfFOinO8xl0w4Q== rmcgeer@rmcgeer-nc4010'

  - name: Set up extra disk
    shell: /usr/testbed/bin/mkextrafs /mnt
      creates=/mnt/local

  - name: Docker config file
    template: src=templates/docker
      dest=/etc/default/docker
    notify:
    - restart docker

  - name: Install "dosh", the Docker shell for GEE
    copy: src=files/dosh
      dest=/usr/local/sbin/dosh
      mode=0755

  - name: Configure monit
    copy: src=files/{{ item }}
      dest=/etc/monit/conf.d/{{ item }}
    with_items:
    - docker.conf
    - http.conf
    - xvda1.conf
    notify:
    - restart monit

  handlers:
  - name: restart docker
    shell: "service docker stop; ip link del docker0; service docker start"

  - name: restart monit
    service: name=monit state=restarted
